version: '3'
services:

  #Composer
  composer:
    image: composer
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: ['bash', 'composer.sh']

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  webserver:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx/key-https.sh:/scripts/key-https.sh
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/certs:/var/www/nginx/certs
      - ./storage/logs/nginx:/var/www/storage/logs/nginx
    entrypoint: ['bash', '/scripts/key-https.sh']

  #MySQL Service
  db:
    image: mysql:5.7.22
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: ngothuyhoa
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

#Volumes
volumes:
  dbdata:
    driver: local