version: '3'
services:

  #Composer
  composer:
    image: composer
    volumes:
      - ./:/var/www
    working_dir: /var/www
    # networks:
    #   - app-network
    entrypoint: ['bash', 'composer.sh']

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "81:80"
      - "443:443"
    tty: true
    volumes:
      - ./key-https.sh:/scripts/key-https.sh
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/var/www/nginx/certs
      - ./storage/logs/nginx:/var/www/storage/logs/nginx
      - .:/var/www
    # working_dir: /var/www
    networks:
      - app-network
    command: [/bin/bash, /scripts/key-https.sh]

  #MySQL Service
  db:
    image: mysql:5.7.22
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: ngothuyhoa
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
# #Volumes
volumes:
  dbdata:
    driver: local